version: 2
updates:
  - package-ecosystem: cargo
    directory: "geopolars/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
  - package-ecosystem: cargo
    directory: "py-geopolars/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
