# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Default to Python 3
default_language_version:
  python: python3

# Optionally both commit and push
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: py-geopolars/

  # This breaks with a UnicodeDecodeError for some reason
  # - repo: https://github.com/keewis/blackdoc
  #   rev: v0.3.6
  #   hooks:
  #     - id: blackdoc
  #       files: py-geopolars/
  #       args: [--check]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: py-geopolars/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        files: py-geopolars/
        args: [--config=py-geopolars/.flake8]
