[workspace]
members = ["geopolars/geopolars-arrow", "geopolars/geopolars-extension"]
exclude = ["py-geopolars", "wasm-geopolars"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.4"
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/geopolars/geopolars"
rust-version = "1.85"
categories = ["science::geo"]

[workspace.dependencies]
arrow-array = { version = "56", features = ["ffi"] }
arrow-buffer = "56"
arrow-data = { version = "56", features = ["ffi"] }
arrow-schema = "56"
geoarrow-array = "0.6"
geoarrow-schema = "0.6"
geopolars-arrow = { path = "geopolars/geopolars-arrow" }
polars = { git = "https://github.com/pola-rs/polars", rev = "0c6dca54ae4a33b3f31191748ad6a5ffd5452822", features = [
    "dtype-extension",
] }
polars-core = { git = "https://github.com/pola-rs/polars", rev = "0c6dca54ae4a33b3f31191748ad6a5ffd5452822", features = [
    "dtype-extension",
] }
polars-arrow = { git = "https://github.com/pola-rs/polars", rev = "0c6dca54ae4a33b3f31191748ad6a5ffd5452822" }
