[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "geopolars"
version = "0.1.0-alpha.4"
dependencies = [
  # Minimum version with binary dtype
  "polars>=0.14.19",
  "pyarrow>=4.0.*",
  "numpy >= 1.16.0",
  "importlib_resources; python_version < '3.11'",
  # For easy interop with geoarrow
  "shapely >= 2.0",
]
requires-python = ">=3.8"
description = "Geospatial extensions for Polars"
readme = "README.md"
# Specify SPDX expression in Cargo.toml instead of here
# https://maturin.rs/metadata.html#add-spdx-license-expressions
# license = "MIT"
authors = [{ name = "Kyle Barron" }, { name = "Stuart Lynn" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: GIS",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Rust",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]

[project.urls]
repository = "https://github.com/geopolars/geopolars"

[tool.isort]
profile = "black"
known_first_party = ["geopolars"]

[tool.mypy]
check_untyped_defs = true
files = ["python/**/*.py", "tests/**/*.py"]
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["pyarrow.*", "geopandas.*", "importlib_resources.*"]
ignore_missing_imports = true

# [tool.coverage.report]
# exclude_lines = ["pragma: no cover", "@overload"]
