[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "geopolars"
version = "0.1.0-alpha.3"
dependencies = [
  # Polars 0.14.19 is a breaking change for us. That patch release adds BinaryArray support, which
  # means that data conversions from PyArrow become BinaryArray instead of ListArray<u8>. See
  # https://github.com/geopolars/geopolars/issues/122
  "polars<=0.14.18",
  "pyarrow>=4.0.*",
  "numpy >= 1.16.0"
]
requires-python = ">=3.7"
description = "Geospatial extensions for Polars"
readme = "README.md"
# Specify SPDX expression in Cargo.toml instead of here
# https://maturin.rs/metadata.html#add-spdx-license-expressions
# license = "MIT"
authors = [
  { name = "Kyle Barron" },
  { name = "Stuart Lynn" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: GIS",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Rust",
  "Programming Language :: Python",
]

[project.urls]
repository = "https://github.com/geopolars/geopolars"

[tool.isort]
profile = "black"
known_first_party = ["geopolars"]

[tool.mypy]
check_untyped_defs = true
files = ["python/**/*.py", "tests/**/*.py"]
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["pyarrow.*", "geopandas.*"]
ignore_missing_imports = true

# [tool.coverage.report]
# exclude_lines = ["pragma: no cover", "@overload"]
