name: Build and lint rust

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "geopolars/**"

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Run
        run: cd geopolars && cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - name: Install protobuf
        run: |
          sudo apt-get install libprotobuf-dev protobuf-compiler

      - name: "clippy --all"
        run: cd geopolars && cargo clippy --all --all-features --tests -- -D warnings

  test:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: "cargo test"
        run: cd geopolars && cargo test --all --all-features
