name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Run
        run: cd geopolars && cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install protobuf and GEOS
        run: |
          sudo apt-get install libprotobuf-dev protobuf-compiler libgeos-dev

      - name: "clippy --all"
        run: cd geopolars && cargo clippy --all --all-features --tests -- -D warnings

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install GEOS
        run: |
          sudo apt-get install libgeos-dev

      - name: "cargo check"
        run: cd geopolars && cargo check --all --all-features

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install GEOS
        run: |
          sudo apt-get install libgeos-dev

      - name: "cargo test"
        run: cd geopolars && cargo test --all --all-features
